name: firebase
version: master
summary: These are the Firebase Command Line Interface (CLI) Tools.
description: |
  These tools can be used to :  
  - Deploy code and assets to your Firebase projects
  - Run a local web server for your Firebase Hosting site
  - Interact with data in your Firebase database
  - Import/Export users into/from Firebase Auth


grade: stable
confinement: strict

apps:
  firebase: 
    command: firebase
    plugs:
      - network

parts:
  firebase:
    plugin: nodejs
    node-packages: [firebase-tools]