name: xt
version: git
summary: Tile coordinates to another format converter.
description: |
  xt is a tool that can automatically convert a stream of coordinates
  to another format that is specified. 
  Developed by the MapBox team.

grade: stable
confinement: strict

apps:
  xt: 
    command: bin/xt
    plugs:
      - network

parts:
  xt:
    source: https://github.com/mapbox/xt.git
    plugin: python