name: newman
version: git
summary: The CLI companion for postman.
description: |
  Using Newman, one can effortlessly run and test Postman 
  Collections directly from the command-line. 

  It's built with extensibility in mind so that you can 
  easily integrate it into your continuous integration 
  servers and build systems.

grade: devel
confinement: devmode

apps:
  newman: 
    command: newman
    plugs:
      - network

parts:
  newman:
    plugin: nodejs
    node-packages: [newman]